export const SAMPLE_MARKDOWN = [
  "# 独立开发者的 2026 复盘",
  "",
  "做产品半年，最深的三个体会：",
  "",
  "1. **先找到 100 个愿意付费的人**，再谈增长",
  "2. 功能做减法，体验做加法",
  "3. 内容是最好的获客渠道，Markdown 转图片这个工具就是例证",
  "",
  "> 不要问\"做什么能火\"，要问\"谁的问题我能解决\"。",
  "",
  "# 来自同行的一句话",
  "",
  "> @独立开发者老张",
  "> ![头像](https://api.dicebear.com/9.x/notionists/svg?seed=zhang&backgroundColor=2563eb)",
  "> 工具就该小而美，先服务好 100 个用户，再谈改变世界。",
  "",
  "## 关于工具",
  "",
  "这款工具支持：",
  "",
  "- 标题、加粗、*斜体*、列表、引用",
  "- 行内代码和代码块",
  "- 中英文混排自动加空隙，排版更专业",
  "- 四套主题 + 品牌 Logo 与主题色",
  "",
  "```ts",
  "const users = await getUsers(100);",
  "const paying = users.filter((u) => u.paid);",
  "console.log(`转化率: ${paying.length / users.length}`);",
  "```",
  "",
  "选择适合自己的尺寸：小红书竖图、朋友圈方图、公众号横图，一键导出高清 PNG。",
  "",
  "![配图示例](https://picsum.photos/seed/md2img/900/600)",
  "",
  "---",
  "",
  "扫码关注，一起做独立开发。",
].join("\n");
