import type { ThemeTokens, PosterSize } from "./types";

export const THEMES: ThemeTokens[] = [
  {
    id: "clean",
    name: "简约白",
    category: "经典",
    description: "白底纯粹，思源黑体，呼吸感大留白",
    previewColors: ["#ffffff", "#111827", "#2563eb"],
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    text: "#27272a",
    heading: "#09090b",
    accent: "#2563eb",
    quoteBg: "#f8fafc",
    quoteBar: "#2563eb",
    codeBg: "#f1f5f9",
    codeBlockBg: "#f8fafc",
    codeBlockBorder: "#e2e8f0",
    hr: "#e2e8f0",
    padding: 72,
    fontHeading: "Noto Sans SC",
    fontBody: "Noto Sans SC",
    fontMono: "JetBrains Mono",
    lineHeight: 1.8,
    fontSize: { h1: 56, h2: 38, h3: 32, body: 28, quote: 26, code: 22, small: 20 },
    headingWeight: 700,
    headingStyle: "bar",
    align: "left",
    showBrandHeader: true,
    footerColor: "#94a3b8",
    isDark: false,
    codeSyntaxTheme: "light",
  },
  {
    id: "trend",
    name: "得意潮酷",
    category: "潮流",
    description: "得意黑大字冲击，曜石黑撞荧光黄，爆款海报",
    previewColors: ["#0f1013", "#ffffff", "#ffe600"],
    background: "#0f1013",
    border: "1px solid #232733",
    text: "#e2e8f0",
    heading: "#ffffff",
    accent: "#ffe600",
    quoteBg: "#1a1c23",
    quoteBar: "#ffe600",
    codeBg: "#1e2129",
    codeBlockBg: "#14161d",
    codeBlockBorder: "#2a2e3d",
    hr: "#2a2e3d",
    padding: 72,
    fontHeading: "Smiley Sans",
    fontBody: "Noto Sans SC",
    fontMono: "JetBrains Mono",
    lineHeight: 1.8,
    fontSize: { h1: 62, h2: 42, h3: 32, body: 28, quote: 26, code: 22, small: 20 },
    headingWeight: 700,
    headingStyle: "pill",
    align: "left",
    showBrandHeader: true,
    footerColor: "#94a3b8",
    isDark: true,
    codeSyntaxTheme: "dark",
  },
  {
    id: "aurora",
    name: "极光夜色",
    category: "潮流",
    description: "深邃夜空渐变，紫霓流光，现代技术发布质感",
    previewColors: ["#0b0f19", "#f8fafc", "#a855f7"],
    background: "#0b0f19",
    backgroundImage: "linear-gradient(145deg, #0b0f19 0%, #111827 50%, #1e1338 100%)",
    border: "1px solid rgba(168, 85, 247, 0.25)",
    text: "#cbd5e1",
    heading: "#f8fafc",
    accent: "#a855f7",
    quoteBg: "rgba(168, 85, 247, 0.1)",
    quoteBar: "#a855f7",
    codeBg: "#181a2e",
    codeBlockBg: "#0f1322",
    codeBlockBorder: "#272c45",
    hr: "#272c45",
    padding: 72,
    fontHeading: "Noto Sans SC",
    fontBody: "Noto Sans SC",
    fontMono: "JetBrains Mono",
    lineHeight: 1.8,
    fontSize: { h1: 56, h2: 38, h3: 32, body: 28, quote: 26, code: 22, small: 20 },
    headingWeight: 700,
    headingStyle: "bar",
    align: "left",
    showBrandHeader: true,
    footerColor: "#64748b",
    isDark: true,
    codeSyntaxTheme: "aurora",
  },
  {
    id: "editorial",
    name: "报章社论",
    category: "经典",
    description: "象牙米纸，经典宋体与英文衬线，深度智识感",
    previewColors: ["#fbf8f2", "#181512", "#991b1b"],
    background: "#fbf8f2",
    border: "2px solid #e5dccb",
    text: "#2c2825",
    heading: "#181512",
    accent: "#991b1b",
    quoteBg: "#f4eee1",
    quoteBar: "#991b1b",
    codeBg: "#f0e8d8",
    codeBlockBg: "#f6f0e4",
    codeBlockBorder: "#e4dac6",
    hr: "#dfd3bd",
    padding: 72,
    fontHeading: "Playfair Display",
    fontBody: "Noto Serif SC",
    fontMono: "JetBrains Mono",
    lineHeight: 1.85,
    fontSize: { h1: 58, h2: 40, h3: 32, body: 28, quote: 26, code: 22, small: 20 },
    headingWeight: 700,
    headingStyle: "underline",
    align: "left",
    showBrandHeader: true,
    footerColor: "#8c8273",
    isDark: false,
    codeSyntaxTheme: "light",
  },
  {
    id: "dark",
    name: "暗夜代码",
    category: "极客",
    description: "深炭蓝黑配霓虹青绿，代码编辑器沉浸感",
    previewColors: ["#0b1020", "#e8f1ff", "#38e1d8"],
    background: "#0b1020",
    border: "1px solid #19233f",
    text: "#b8c7e0",
    heading: "#e8f1ff",
    accent: "#38e1d8",
    quoteBg: "#131a30",
    quoteBar: "#38e1d8",
    codeBg: "#131a30",
    codeBlockBg: "#0d1428",
    codeBlockBorder: "#1e2a4a",
    hr: "#1e2a4a",
    padding: 72,
    fontHeading: "Noto Sans SC",
    fontBody: "Noto Sans SC",
    fontMono: "JetBrains Mono",
    lineHeight: 1.8,
    fontSize: { h1: 56, h2: 38, h3: 32, body: 28, quote: 26, code: 22, small: 20 },
    headingWeight: 700,
    headingStyle: "bar",
    align: "left",
    showBrandHeader: true,
    footerColor: "#5c6b8a",
    isDark: true,
    codeSyntaxTheme: "dark",
  },
  {
    id: "warm",
    name: "暖杏文艺",
    category: "文艺",
    description: "温润奶油底，霞鹜文楷手写笔触，静谧治愈",
    previewColors: ["#faf5ee", "#2d2620", "#c2653c"],
    background: "#faf5ee",
    border: "1px solid #ebdfcd",
    text: "#4a3f35",
    heading: "#2d2620",
    accent: "#c2653c",
    quoteBg: "#f3ece0",
    quoteBar: "#c2653c",
    codeBg: "#efe7da",
    codeBlockBg: "#f5efe6",
    codeBlockBorder: "#e5dccb",
    hr: "#e0d5c0",
    padding: 72,
    fontHeading: "LXGW WenKai",
    fontBody: "LXGW WenKai",
    fontMono: "JetBrains Mono",
    lineHeight: 1.9,
    fontSize: { h1: 56, h2: 38, h3: 32, body: 28, quote: 26, code: 22, small: 20 },
    headingWeight: 700,
    headingStyle: "pill",
    align: "left",
    showBrandHeader: true,
    footerColor: "#a09080",
    isDark: false,
    codeSyntaxTheme: "warm",
  },
  {
    id: "serif",
    name: "山青墨竹",
    category: "文艺",
    description: "淡青玉底与松柏墨绿，思源宋体，极简东方禅意",
    previewColors: ["#eef4f0", "#1d2a24", "#1f6f50"],
    background: "#eef4f0",
    border: "1px solid #d5dfd8",
    text: "#33413a",
    heading: "#1d2a24",
    accent: "#1f6f50",
    quoteBg: "#e4ece6",
    quoteBar: "#1f6f50",
    codeBg: "#dfe8e2",
    codeBlockBg: "#e8efe9",
    codeBlockBorder: "#d3ded6",
    hr: "#cfdcd3",
    padding: 72,
    fontHeading: "Noto Serif SC",
    fontBody: "Noto Serif SC",
    fontMono: "JetBrains Mono",
    lineHeight: 1.85,
    fontSize: { h1: 56, h2: 38, h3: 32, body: 28, quote: 26, code: 22, small: 20 },
    headingWeight: 700,
    headingStyle: "bar",
    align: "left",
    showBrandHeader: true,
    footerColor: "#7d8f85",
    isDark: false,
    codeSyntaxTheme: "light",
  },
  {
    id: "crt",
    name: "复古 CRT",
    category: "极客",
    description: "老式绿色终端荧光屏，扫描线纹理与全套像素字体",
    previewColors: ["#070d08", "#a4ffc2", "#00ff41"],
    background: "#070d08",
    backgroundImage:
      "linear-gradient(rgba(0, 255, 65, 0.06) 50%, rgba(0, 0, 0, 0) 50%)",
    border: "2px solid #13351d",
    text: "#37d968",
    heading: "#a4ffc2",
    accent: "#00ff41",
    quoteBg: "#0f1c13",
    quoteBar: "#00ff41",
    codeBg: "#0f1c13",
    codeBlockBg: "#040905",
    codeBlockBorder: "#173a22",
    hr: "#173a22",
    padding: 72,
    fontHeading: "Fusion Pixel",
    fontBody: "Fusion Pixel",
    fontMono: "Fusion Pixel",
    lineHeight: 1.8,
    fontSize: { h1: 56, h2: 38, h3: 32, body: 28, quote: 26, code: 22, small: 20 },
    headingWeight: 700,
    headingStyle: "terminal",
    align: "left",
    showBrandHeader: true,
    footerColor: "#2a5c3a",
    isDark: true,
    codeSyntaxTheme: "crt",
  },
  {
    id: "paper",
    name: "琥珀便签",
    category: "文艺",
    description: "桌面便利贴暖黄质感，文楷灵动笔迹，随笔与金句",
    previewColors: ["#fffbeb", "#292524", "#d97706"],
    background: "#fffbeb",
    border: "1px dashed #fcd34d",
    text: "#44403c",
    heading: "#1c1917",
    accent: "#d97706",
    quoteBg: "#fef3c7",
    quoteBar: "#d97706",
    codeBg: "#fef3c7",
    codeBlockBg: "#fffdf5",
    codeBlockBorder: "#fde68a",
    hr: "#fde68a",
    padding: 72,
    fontHeading: "LXGW WenKai",
    fontBody: "Noto Sans SC",
    fontMono: "JetBrains Mono",
    lineHeight: 1.8,
    fontSize: { h1: 56, h2: 38, h3: 32, body: 28, quote: 26, code: 22, small: 20 },
    headingWeight: 700,
    headingStyle: "pill",
    align: "left",
    showBrandHeader: true,
    footerColor: "#a8a29e",
    isDark: false,
    codeSyntaxTheme: "warm",
  },
  {
    id: "mint",
    name: "苏打薄荷",
    category: "潮流",
    description: "清爽薄荷青与冰川蓝，通透元气，教程科普首选",
    previewColors: ["#f0fdfa", "#042f2e", "#0d9488"],
    background: "#f0fdfa",
    border: "1px solid #99f6e4",
    text: "#134e4a",
    heading: "#042f2e",
    accent: "#0d9488",
    quoteBg: "#ccfbf1",
    quoteBar: "#0d9488",
    codeBg: "#ccfbf1",
    codeBlockBg: "#f0fdfa",
    codeBlockBorder: "#99f6e4",
    hr: "#99f6e4",
    padding: 72,
    fontHeading: "Noto Sans SC",
    fontBody: "Noto Sans SC",
    fontMono: "JetBrains Mono",
    lineHeight: 1.8,
    fontSize: { h1: 56, h2: 38, h3: 32, body: 28, quote: 26, code: 22, small: 20 },
    headingWeight: 700,
    headingStyle: "bar",
    align: "left",
    showBrandHeader: true,
    footerColor: "#0d9488",
    isDark: false,
    codeSyntaxTheme: "light",
  },
];

export const SIZES: PosterSize[] = [
  { id: "xiaohongshu", name: "小红书竖图", width: 1080, minHeight: 1350, ratio: "3:4" },
  { id: "square", name: "朋友圈方图", width: 1080, minHeight: 1080, ratio: "1:1" },
  { id: "landscape", name: "公众号横图", width: 1200, minHeight: 630, ratio: "16:9" },
  { id: "custom", name: "自定义尺寸", width: 1080, minHeight: 1350, ratio: "自定义" },
];

export const CUSTOM_SIZE_LIMITS = { min: 200, max: 4000 };

export function getSize(id: string): PosterSize {
  return SIZES.find((s) => s.id === id) ?? SIZES[0];
}

export function getTheme(id: string): ThemeTokens {
  return THEMES.find((t) => t.id === id) ?? THEMES[0];
}

/** 自定义尺寸：返回可编辑的宽/高（minHeight 即高度） */
export function getCustomSize(custom: { width: number; height: number }): PosterSize {
  const clamp = (n: number) => Math.min(CUSTOM_SIZE_LIMITS.max, Math.max(CUSTOM_SIZE_LIMITS.min, Math.round(n) || CUSTOM_SIZE_LIMITS.min));
  return {
    id: "custom",
    name: "自定义尺寸",
    width: clamp(custom.width),
    minHeight: clamp(custom.height),
    ratio: `${clamp(custom.width)}×${clamp(custom.height)}`,
  };
}
